//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod assigned_staff;
pub mod destination;
pub mod passenger;
pub mod passenger_creds;
pub mod person;
pub mod roadmap;
pub mod route;
pub mod route_destination;
pub mod route_notification;
pub mod seat;
pub mod staff;
pub mod staff_creds;
pub mod station;
pub mod ticket;
pub mod train;
