//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "route_destination")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub route_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub destination_id: Uuid,
    #[sea_orm(column_type = "Float")]
    pub destination_order: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::destination::Entity",
        from = "Column::DestinationId",
        to = "super::destination::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Destination,
    #[sea_orm(
        belongs_to = "super::route::Entity",
        from = "Column::RouteId",
        to = "super::route::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Route,
}

impl Related<super::destination::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Destination.def()
    }
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
