//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "route_notification")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub route_id: Uuid,
    pub last_notis_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::route::Entity",
        from = "Column::RouteId",
        to = "super::route::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Route,
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
