//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "route")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub train_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::route_destination::Entity")]
    RouteDestination,
    #[sea_orm(
        belongs_to = "super::train::Entity",
        from = "Column::TrainId",
        to = "super::train::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Train,
}

impl Related<super::route_destination::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RouteDestination.def()
    }
}

impl Related<super::train::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Train.def()
    }
}

impl Related<super::destination::Entity> for Entity {
    fn to() -> RelationDef {
        super::route_destination::Relation::Destination.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::route_destination::Relation::Route.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
