//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "staff")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub person_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assigned_staff::Entity")]
    AssignedStaff,
    #[sea_orm(
        belongs_to = "super::person::Entity",
        from = "Column::PersonId",
        to = "super::person::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Person,
    #[sea_orm(has_many = "super::staff_creds::Entity")]
    StaffCreds,
}

impl Related<super::assigned_staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedStaff.def()
    }
}

impl Related<super::person::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Person.def()
    }
}

impl Related<super::staff_creds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffCreds.def()
    }
}

impl Related<super::train::Entity> for Entity {
    fn to() -> RelationDef {
        super::assigned_staff::Relation::Train.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::assigned_staff::Relation::Staff.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
