//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod assigned_staff;
pub mod destinations;
pub mod passenger;
pub mod person;
pub mod roadmaps;
pub mod route_destinations;
pub mod routes;
pub mod seat;
pub mod staff;
pub mod stations;
pub mod ticket;
pub mod trains;
