//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::assigned_staff::Entity as AssignedStaff;
pub use super::destination::Entity as Destination;
pub use super::passenger::Entity as Passenger;
pub use super::person::Entity as Person;
pub use super::roadmaps::Entity as Roadmaps;
pub use super::route_destination::Entity as RouteDestination;
pub use super::routes::Entity as Routes;
pub use super::seat::Entity as Seat;
pub use super::staff::Entity as Staff;
pub use super::stations::Entity as Stations;
pub use super::ticket::Entity as Ticket;
pub use super::trains::Entity as Trains;
