//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "roadmaps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub destination: String,
    pub start: String,
    pub estimated_time: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::destinations::Entity")]
    Destinations,
}

impl Related<super::destinations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Destinations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
