[package]
name = "entity_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = "0.12.3"
serde = { version = "1.0.188", features = ["derive"] }
