[package]
name = "user_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ring = "0.17.2"
sqlx = { version = "0.7.2", features = ["sqlx-sqlite", "runtime-tokio"] }
